format_version: 10
pipelines:
  local_repo:
    group: specs_store
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-7dab074:
        git: file:///Users/yatindra.khandal/workspace/studywork/spakes_store/
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          npm-install-n-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - i
                command: npm
                run_if: passed
            - exec:
                arguments:
                - run
                - build
                command: npm
                run_if: passed
